//
//  GovCountryCodes.swift
//  mandayFaktura
//
//  Created by Wojciech Kicior on 07/01/2024.
//  Copyright © 2024 Wojciech Kicior. All rights reserved.
//

import Foundation

class GovCountryCodes {
    private static let namesToCodes = [
        "AFGANISTAN": "AF",
        "ALAND ISLANDS": "AX",
        "ALBANIA": "AL",
        "ALGIERIA": "DZ",
        "ANDORA": "AD",
        "ANGOLA": "AO",
        "ANGUILLA": "AI",
        "ANTARKTYDA": "AQ",
        "ANTIGUA I BARBUDA": "AG",
        "ANTYLE HOLENDERSKIE": "AN",
        "ARABIA SAUDYJSKA": "SA",
        "ARGENTYNA": "AR",
        "ARMENIA": "AM",
        "ARUBA": "AW",
        "AUSTRALIA": "AU",
        "AUSTRIA": "AT",
        "AZERBEJDŻAN": "AZ",
        "BAHAMY": "BS",
        "BAHRAJN": "BH",
        "BANGLADESZ": "BD",
        "BARBADOS": "BB",
        "BELGIA": "BE",
        "BELIZE": "BZ",
        "BENIN": "BJ",
        "BERMUDY": "BM",
        "BHUTAN": "BT",
        "BIAŁORUŚ": "BY",
        "BOLIWIA": "BO",
        "BONAIRE, SINT EUSTATIUS I SABA": "BQ",
        "BOŚNIA I HERCEGOWINA": "BA",
        "BOTSWANA": "BW",
        "BRAZYLIA": "BR",
        "BRUNEI DARUSSALAM": "BN",
        "BRYTYJSKIE TERYTORIUM OCEANU INDYJSKIEGO": "IO",
        "BUŁGARIA": "BG",
        "BURKINA FASO": "BF",
        "BURUNDI": "BI",
        "CEUTA": "XC",
        "CHILE": "CL",
        "CHINY": "CN",
        "CHORWACJA": "HR",
        "CURAÇAO": "CW",
        "CYPR": "CY",
        "CZAD": "TD",
        "CZARNOGÓRA": "ME",
        "DANIA": "DK",
        "DOMINIKA": "DM",
        "DOMINIKANA": "DO",
        "DŻIBUTI": "DJ",
        "EGIPT": "EG",
        "EKWADOR": "EC",
        "ERYTREA": "ER",
        "ESTONIA": "EE",
        "ETIOPIA": "ET",
        "FALKLANDY": "FK",
        "FIDŻI REPUBLIKA": "FJ",
        "FILIPINY": "PH",
        "FINLANDIA": "FI",
        "FRANCJA": "FR",
        "FRANCUSKIE TERYTORIUM POŁUDNIOWE": "TF",
        "GABON": "GA",
        "GAMBIA": "GM",
        "GHANA": "GH",
        "GIBRALTAR": "GI",
        "GRECJA": "GR",
        "GRENADA": "GD",
        "GRENLANDIA": "GL",
        "GRUZJA": "GE",
        "GUAM": "GU",
        "GUERNSEY": "GG",
        "GUJANA": "GY",
        "GUJANA FRANCUSKA": "GF",
        "GWADELUPA": "GP",
        "GWATEMALA": "GT",
        "GWINEA": "GN",
        "GWINEA RÓWNIKOWA": "GQ",
        "GWINEA-BISSAU": "GW",
        "HAITI": "HT",
        "HISZPANIA": "ES",
        "HONDURAS": "HN",
        "HONGKONG": "HK",
        "INDIE": "IN",
        "INDONEZJA": "ID",
        "IRAK": "IQ",
        "IRAN": "IR",
        "IRLANDIA": "IE",
        "ISLANDIA": "IS",
        "IZRAEL": "IL",
        "JAMAJKA": "JM",
        "JAPONIA": "JP",
        "JEMEN": "YE",
        "JERSEY": "JE",
        "JORDANIA": "JO",
        "KAJMANY": "KY",
        "KAMBODŻA": "KH",
        "KAMERUN": "CM",
        "KANADA": "CA",
        "KATAR": "QA",
        "KAZACHSTAN": "KZ",
        "KENIA": "KE",
        "KIRGISTAN": "KG",
        "KIRIBATI": "KI",
        "KOLUMBIA": "CO",
        "KOMORY": "KM",
        "KONGO": "CG",
        "KONGO, REPUBLIKA DEMOKRATYCZNA": "CD",
        "KOREAŃSKA REPUBLIKA LUDOWO-DEMOKRATYCZNA": "KP",
        "KOSOWO": "XK",
        "KOSTARYKA": "CR",
        "KUBA": "CU",
        "KUWEJT": "KW",
        "LAOS": "LA",
        "LESOTHO": "LS",
        "LIBAN": "LB",
        "LIBERIA": "LR",
        "LIBIA": "LY",
        "LIECHTENSTEIN": "LI",
        "LITWA": "LT",
        "ŁOTWA": "LV",
        "LUKSEMBURG": "LU",
        "MACEDONIA": "MK",
        "MADAGASKAR": "MG",
        "MAJOTTA": "YT",
        "MAKAU": "MO",
        "MALAWI": "MW",
        "MALEDIWY": "MV",
        "MALEZJA": "MY",
        "MALI": "ML",
        "MALTA": "MT",
        "MARIANY PÓŁNOCNE": "MP",
        "MAROKO": "MA",
        "MARTYNIKA": "MQ",
        "MAURETANIA": "MR",
        "MAURITIUS": "MU",
        "MEKSYK": "MX",
        "MELILLA": "XL",
        "MIKRONEZJA": "FM",
        "MINOR": "UM",
        "MOŁDOWA": "MD",
        "MONAKO": "MC",
        "MONGOLIA": "MN",
        "MONTSERRAT": "MS",
        "MOZAMBIK": "MZ",
        "MYANMAR (BURMA)": "MM",
        "NAMIBIA": "NA",
        "NAURU": "NR",
        "NEPAL": "NP",
        "NIDERLANDY (HOLANDIA)": "NL",
        "NIEMCY": "DE",
        "NIGER": "NE",
        "NIGERIA": "NG",
        "NIKARAGUA": "NI",
        "NIUE": "NU",
        "NORFOLK": "NF",
        "NORWEGIA": "NO",
        "NOWA KALEDONIA": "NC",
        "NOWA ZELANDIA": "NZ",
        "OKUPOWANE TERYTORIUM PALESTYNY": "PS",
        "OMAN": "OM",
        "PAKISTAN": "PK",
        "PALAU": "PW",
        "PANAMA": "PA",
        "PAPUA NOWA GWINEA": "PG",
        "PARAGWAJ": "PY",
        "PERU": "PE",
        "PITCAIRN": "PN",
        "POLINEZJA FRANCUSKA": "PF",
        "POLSKA": "PL",
        "POŁUDNIOWA GEORGIA I POŁUD.WYSPY SANDWICH": "GS",
        "PORTUGALIA": "PT",
        "PORTORYKO": "PR",
        "REP.ŚRODKOWOAFRYKAŃSKA": "CF",
        "REPUBLIKA CZESKA": "CZ",
        "REPUBLIKA KOREI": "KR",
        "REPUBLIKA POŁUDNIOWEJ AFRYKI": "ZA",
        "REUNION": "RE",
        "ROSJA": "RU",
        "RUMUNIA": "RO",
        "RWANDA": "RW",
        "SAHARA ZACHODNIA": "EH",
        "SAINT BARTHELEMY": "BL",
        "SAINT KITTS I NEVIS": "KN",
        "SAINT LUCIA": "LC",
        "SAINT MARTIN": "MF",
        "SAINT VINCENT I GRENADYNY": "VC",
        "SALWADOR": "SV",
        "SAMOA": "WS",
        "SAMOA AMERYKAŃSKIE": "AS",
        "SAN MARINO": "SM",
        "SENEGAL": "SN",
        "SERBIA": "RS",
        "SESZELE": "SC",
        "SIERRA LEONE": "SL",
        "SINGAPUR": "SG",
        "SŁOWACJA": "SK",
        "SŁOWENIA": "SI",
        "SOMALIA": "SO",
        "SRI LANKA": "LK",
        "SAINT PIERRE I MIQUELON": "PM",
        "STANY ZJEDNOCZONE AMERYKI": "US",
        "SUAZI": "SZ",
        "SUDAN": "SD",
        "SUDAN POŁUDNIOWY": "SS",
        "SURINAM": "SR",
        "SVALBARD I JAN MAYEN": "SJ",
        "ŚWIĘTA HELENA": "SH",
        "SYRIA": "SY",
        "SZWAJCARIA": "CH",
        "SZWECJA": "SE",
        "TADŻYKISTAN": "TJ",
        "TAJLANDIA": "TH",
        "TAJWAN": "TW",
        "TANZANIA": "TZ",
        "TOGO": "TG",
        "TOKELAU": "TK",
        "TONGA": "TO",
        "TRYNIDAD I TOBAGO": "TT",
        "TUNEZJA": "TN",
        "TURCJA": "TR",
        "TURKMENISTAN": "TM",
        "TUVALU": "TV",
        "UGANDA": "UG",
        "UKRAINA": "UA",
        "URUGWAJ": "UY",
        "UZBEKISTAN": "UZ",
        "VANUATU": "VU",
        "WALLIS I FUTUNA": "WF",
        "WATYKAN": "VA",
        "WĘGRY": "HU",
        "WENEZUELA": "VE",
        "WIELKA BRYTANIA": "GB",
        "WIETNAM": "VN",
        "WŁOCHY": "IT",
        "WSCHODNI TIMOR": "TL",
        "WYBRZEŻE KOŚCI SŁONIOWEJ": "CI",
        "WYSPA BOUVETA": "BV",
        "WYSPA BOŻEGO NARODZENIA": "CX",
        "WYSPA MAN": "IM",
        "WYSPA SINT MAARTEN (CZĘŚĆ HOLENDERSKA WYSPY)": "SX",
        "WYSPY COOKA": "CK",
        "WYSPY DZIEWICZE-USA": "VI",
        "WYSPY DZIEWICZE-W.B.": "VG",
        "WYSPY HEARD I MCDONALD": "HM",
        "WYSPY KOKOSOWE (KEELINGA)": "CC",
        "WYSPY MARSHALLA": "MH",
        "WYSPY OWCZE": "FO",
        "WYSPY SALOMONA": "SB",
        "WYSPY ŚWIĘTEGO TOMASZA I KSIĄŻĘCA": "ST",
        "WYSPY TURKS I CAICOS": "TC",
        "ZAMBIA": "ZM",
        "ZIELONY PRZYLĄDEK": "CV",
        "ZIMBABWE": "ZW",
        "ZJEDNOCZONE EMIRATY ARABSKIE": "AE",
        "ZJEDNOCZONE KRÓLESTWO (IRLANDIA PÓŁNOCNA)": "XI"
    ]
    
    public static func getCodeByName(countryName: String) -> String? {
        return GovCountryCodes.namesToCodes[countryName.uppercased()]
    }
}
